### ISSUE TITLE
Login does not provide feedback on reoccurring errors

### ISSUE THREAD

**Issue by Applemelon** [JanvanZetten/BazarFrontEnd#22]
![image](https://user-images.githubusercontent.com/32298607/49572432-12966400-f93c-11e8-8f62-2d59a4dc6001.png)

The error message should be removed when clicking the login button again, and then pop up later if login failed. This gives the user feedback on the process of their login attempts.

**Comment by JanvanZetten** [comment]
I am working on solving this issue

**Comment by JanvanZetten** [comment]
💻

**Comment by JanvanZetten** [comment]
🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🇳🇱🖥⌨️🖱💻📱⌚️

**Comment by JanvanZetten** [comment]
🇬🇷🇳🇱🇮🇸🇰🇵🇬🇧🇩🇰🇺🇳

**Comment by JanvanZetten** [comment]
The Alerts are now dismissible, they wannish after 5 seconds and there can be more than one. The solution is here: #43
